language: cpp

before_install:
 - sudo apt-get update -q
 - sudo apt-get install libcppunit-dev -y
 - sudo apt-get install libsqlite3-dev -y
 - sudo apt-get install doxygen
 - sudo apt-get install lcov
 
script: 
 - mkdir -p ./build/gcc/Debug
 - mkdir -p ./build/gcc/Release
 - mkdir -p ./build/gcc/Coverage
 - cd build/gcc/Debug
 - cmake ../../.. -DCMAKE_BUILD_TYPE=Debug
 - make
 - ./saturnin-test
 - make doc
 - cp -R doc ../../../docs/
 - cd ../../gcc/Release
 - cmake ../../.. -DCMAKE_BUILD_TYPE=Release
 - make
 - cd ../../..
 - cd build/gcc/Coverage
 - cmake ../../.. -DCMAKE_BUILD_TYPE=Coverage
 - make saturnin-coverage
 - cp -R saturnin-coverage ../../../docs/coverage
 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  local_dir: docs
  on:
    branch: master